### ISSUE TITLE
pubstats.py actively refusing connection

### ISSUE THREAD

**Issue by Fitzy-cmd** [Slaymish/EchoStatsFinder#1]
Executing pubstats.py results in a runtime error with the following error message:
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=6721): Max retries exceeded with url: /session (Caused 
by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026CC1BDA310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

Possible issues involve a potentially incorrect port or firewall. If these are possible causes, maybe add option for port change?

If not, any other ideas as to the possible cause?

**Comment by Slaymish** [comment]
Pretty sure the only port the echo session api runs on is 6721. Though I did add a port selection in ip.txt if you want to change it. The only way I could replicate your error was by not having echo open. Make sure its open and you have api access turned on in echo settings. If thats not working, test it with spark spectator stream and see if that works

**Comment by Slaymish** [comment]
Just tried on both my quest and pc, its working fine for me. Run off same api as spark, so if spark works, this should too
