### ISSUE TITLE
Fatal Error: Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by Slaymish** [Slaymish/EchoStatsFinder#6]
Getting this error whenever I press either of the search buttons.

<img width="1210" alt="error" src="https://user-images.githubusercontent.com/21288505/139836078-eb2b2f42-b45c-465f-96d8-2a6bd7b010d1.png">

**Comment by Fitzy-cmd** [comment]
Resolved by adding certificate to the local folder and updating some of the code.
